service: sls-aws-cicd
frameworkVersion: '3'
provider: 
  name: aws
  runtime: nodejs18.x
  lambdaHashingVersion: 20201221
  stage: dev
  region: ap-southeast-2
functions:
  getVersion:
    handler: handler.getVersion
    events:
      - http:
          path: /get-version
          method: GET    
